# Generated by Django 2.1.7 on 2019-03-03 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Comm_text', models.TextField()),
                ('Comm_submited_by', models.CharField(max_length=30)),
                ('Comm_submited_at', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('Serv_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('Team_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Team_start_time', models.TimeField()),
                ('Team_end_time', models.TimeField()),
                ('Team_serv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RTML_app.Service')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comm_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RTML_app.Team'),
        ),
    ]
