# Generated by Django 2.1.7 on 2019-07-16 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RTML_app', '0002_remove_comment_comm_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Comm_team',
            field=models.ForeignKey(default='Select Service', on_delete=django.db.models.deletion.PROTECT, to='RTML_app.Team'),
            preserve_default=False,
        ),
    ]
