# Generated by Django 2.1.7 on 2019-07-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RTML_app', '0004_auto_20190717_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServName', models.CharField(max_length=60)),
            ],
        ),
    ]
