# Generated by Django 2.1.7 on 2019-07-16 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RTML_app', '0005_servicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('TeamName', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='ServName',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='TeamServ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RTML_app.ServiceModel'),
        ),
    ]
